### ISSUE TITLE
LICENSE.txt

### ISSUE THREAD

**Issue by davelab6** [EbenSorkin/EQX-Test-Visual-Samples#2]
Please add a LICENSE.txt, AUTHORS.txt and CONTRIBUTORS.txt files

**Comment by EbenSorkin** [comment]
Thanks! Will do

**Comment by EbenSorkin** [comment]
It would be best for it to have the same License as EQX I think. Agreed?

**Comment by EbenSorkin** [comment]
I have added the AUTHORS.txt and CONTRIBUTORS.txt files

**Comment by EbenSorkin** [comment]
Quinn added the EQX license. We can revise this but I think this is probably closed.

**Comment by davelab6** [comment]
Perfect thank you
